--- 
stages: 
  - name: Build
    inputs: 
      - type: git
        branch: master
    triggers: 
      - type: commit
    jobs: 
      - name: Build
        type: builder
  - name: Deploy
    inputs: 
      - type: job
        stage: Build
        job: Build
    triggers: 
      - type: stage
    jobs: 
      - name: dev
        type: deployer
        script: |-
            #!/bin/bash
            CLOUDANT_NAME="letwatsonguess-cloudantNoSQLDB"
            cf push "${CF_APP}" --no-start
            cf set-env "${CF_APP}" NODE_RED_STORAGE_NAME "${CLOUDANT_NAME}"
            cf create-service cloudantNoSQLDB Lite "${CLOUDANT_NAME}"
            for i in `seq 1 100`; do
              RESULT=`cf service ${CLOUDANT_NAME} | grep status: | awk '{print $3}'`
              if [ $RESULT == "succeeded" ]; then
                break
              fi
            done
            cf bind-service "${CF_APP}" "${CLOUDANT_NAME}" -c '{"role":"Manager"}'
            cf start "${CF_APP}"
            # View logs
            cf logs "${CF_APP}" --recent
        target:
          region_id: ${CF_REGION_ID}
          organization: ${CF_ORGANIZATION}
          space: ${CF_SPACE}
          application: ${CF_APP}
          api_key: ${API_KEY}
